run_name: WikiDiverse
seed: 43
pretrained_model: 'openai/clip-vit-base-patch32'
lr: 3e-5


data:
  num_entity: 132460
  kb_img_folder: /path/to/datasets/WikiDiverse/kb_image/kb_image
  mention_img_folder: /path/to/datasets/WikiDiverse/mention_image/mention_image
  qid2id: /path/to/datasets/WikiDiverse/qid2id.json
  entity: /path/to/datasets/WikiDiverse/kb_entity.json

  train_file: /path/to/datasets/WikiDiverse/wiki_diverse_train.json
  dev_file: /path/to/datasets/WikiDiverse/wiki_diverse_dev.json
  test_file: /path/to/datasets/WikiDiverse/wiki_diverse_test.json
  hard_neg_file: /path/to/hard_negatives/wikidiverse_hard_negatives.json
  test_ckpt: null

  num_hard_negatives: 1
  batch_size: 128
  num_workers: 8
  text_max_length: 60

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96
  loss_temperature: 0.03
  inter_weight: 1.0
  intra_weight: 0.8
  with_cl_loss: 1



trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  precision: 16
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30

